<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxMLQCy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxMLQCy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxMLQCy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxMLQCy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxMLQCy\App_KernelDevDebugContainer([
    'container.build_hash' => 'TxMLQCy',
    'container.build_id' => '48bb8b6e',
    'container.build_time' => 1729718361,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxMLQCy');
