<?php

namespace ContainerTxMLQCy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5PmtLLIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5PmtLLI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5PmtLLI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'library' => ['privates', '.errored..service_locator.5PmtLLI.App\\Entity\\Library', NULL, 'Cannot autowire service ".service_locator.5PmtLLI": it needs an instance of "App\\Entity\\Library" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'library' => 'App\\Entity\\Library',
        ]);
    }
}
