<?php

namespace ContainerTxMLQCy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YbdrZYoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YbdrZYo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YbdrZYo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CrudAuthorController::SearchByName' => ['privates', '.service_locator.XzfvUL_', 'get_ServiceLocator_XzfvULService', true],
            'App\\Controller\\CrudAuthorController::UpdateAuthor' => ['privates', '.service_locator.udgqdgD', 'get_ServiceLocator_UdgqdgDService', true],
            'App\\Controller\\CrudAuthorController::deleteAuthor' => ['privates', '.service_locator.udgqdgD', 'get_ServiceLocator_UdgqdgDService', true],
            'App\\Controller\\CrudAuthorController::list' => ['privates', '.service_locator.XzfvUL_', 'get_ServiceLocator_XzfvULService', true],
            'App\\Controller\\CrudAuthorController::newAuthor' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CrudAuthorController::searchByLibrary' => ['privates', '.service_locator.N7RYgGs', 'get_ServiceLocator_N7RYgGsService', true],
            'App\\Controller\\CrudBookController::deleteBook' => ['privates', '.service_locator.qo8rK6B', 'get_ServiceLocator_Qo8rK6BService', true],
            'App\\Controller\\CrudBookController::list' => ['privates', '.service_locator.CJQyp.k', 'get_ServiceLocator_CJQyp_KService', true],
            'App\\Controller\\CrudBookController::newBook' => ['privates', '.service_locator.Fv9x6Se', 'get_ServiceLocator_Fv9x6SeService', true],
            'App\\Controller\\CrudBookController::searchByTitle' => ['privates', '.service_locator.CJQyp.k', 'get_ServiceLocator_CJQyp_KService', true],
            'App\\Controller\\CrudBookController::updateBook' => ['privates', '.service_locator.qo8rK6B', 'get_ServiceLocator_Qo8rK6BService', true],
            'App\\Controller\\CrudLibraryController::SearchByName' => ['privates', '.service_locator.VJntpK4', 'get_ServiceLocator_VJntpK4Service', true],
            'App\\Controller\\CrudLibraryController::deleteLibrary' => ['privates', '.service_locator.5PmtLLI', 'get_ServiceLocator_5PmtLLIService', true],
            'App\\Controller\\CrudLibraryController::list' => ['privates', '.service_locator.VJntpK4', 'get_ServiceLocator_VJntpK4Service', true],
            'App\\Controller\\CrudLibraryController::newLibrary' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CrudLibraryController::updateLibrary' => ['privates', '.service_locator.5PmtLLI', 'get_ServiceLocator_5PmtLLIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CrudAuthorController:SearchByName' => ['privates', '.service_locator.XzfvUL_', 'get_ServiceLocator_XzfvULService', true],
            'App\\Controller\\CrudAuthorController:UpdateAuthor' => ['privates', '.service_locator.udgqdgD', 'get_ServiceLocator_UdgqdgDService', true],
            'App\\Controller\\CrudAuthorController:deleteAuthor' => ['privates', '.service_locator.udgqdgD', 'get_ServiceLocator_UdgqdgDService', true],
            'App\\Controller\\CrudAuthorController:list' => ['privates', '.service_locator.XzfvUL_', 'get_ServiceLocator_XzfvULService', true],
            'App\\Controller\\CrudAuthorController:newAuthor' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CrudAuthorController:searchByLibrary' => ['privates', '.service_locator.N7RYgGs', 'get_ServiceLocator_N7RYgGsService', true],
            'App\\Controller\\CrudBookController:deleteBook' => ['privates', '.service_locator.qo8rK6B', 'get_ServiceLocator_Qo8rK6BService', true],
            'App\\Controller\\CrudBookController:list' => ['privates', '.service_locator.CJQyp.k', 'get_ServiceLocator_CJQyp_KService', true],
            'App\\Controller\\CrudBookController:newBook' => ['privates', '.service_locator.Fv9x6Se', 'get_ServiceLocator_Fv9x6SeService', true],
            'App\\Controller\\CrudBookController:searchByTitle' => ['privates', '.service_locator.CJQyp.k', 'get_ServiceLocator_CJQyp_KService', true],
            'App\\Controller\\CrudBookController:updateBook' => ['privates', '.service_locator.qo8rK6B', 'get_ServiceLocator_Qo8rK6BService', true],
            'App\\Controller\\CrudLibraryController:SearchByName' => ['privates', '.service_locator.VJntpK4', 'get_ServiceLocator_VJntpK4Service', true],
            'App\\Controller\\CrudLibraryController:deleteLibrary' => ['privates', '.service_locator.5PmtLLI', 'get_ServiceLocator_5PmtLLIService', true],
            'App\\Controller\\CrudLibraryController:list' => ['privates', '.service_locator.VJntpK4', 'get_ServiceLocator_VJntpK4Service', true],
            'App\\Controller\\CrudLibraryController:newLibrary' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\CrudLibraryController:updateLibrary' => ['privates', '.service_locator.5PmtLLI', 'get_ServiceLocator_5PmtLLIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CrudAuthorController::SearchByName' => '?',
            'App\\Controller\\CrudAuthorController::UpdateAuthor' => '?',
            'App\\Controller\\CrudAuthorController::deleteAuthor' => '?',
            'App\\Controller\\CrudAuthorController::list' => '?',
            'App\\Controller\\CrudAuthorController::newAuthor' => '?',
            'App\\Controller\\CrudAuthorController::searchByLibrary' => '?',
            'App\\Controller\\CrudBookController::deleteBook' => '?',
            'App\\Controller\\CrudBookController::list' => '?',
            'App\\Controller\\CrudBookController::newBook' => '?',
            'App\\Controller\\CrudBookController::searchByTitle' => '?',
            'App\\Controller\\CrudBookController::updateBook' => '?',
            'App\\Controller\\CrudLibraryController::SearchByName' => '?',
            'App\\Controller\\CrudLibraryController::deleteLibrary' => '?',
            'App\\Controller\\CrudLibraryController::list' => '?',
            'App\\Controller\\CrudLibraryController::newLibrary' => '?',
            'App\\Controller\\CrudLibraryController::updateLibrary' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CrudAuthorController:SearchByName' => '?',
            'App\\Controller\\CrudAuthorController:UpdateAuthor' => '?',
            'App\\Controller\\CrudAuthorController:deleteAuthor' => '?',
            'App\\Controller\\CrudAuthorController:list' => '?',
            'App\\Controller\\CrudAuthorController:newAuthor' => '?',
            'App\\Controller\\CrudAuthorController:searchByLibrary' => '?',
            'App\\Controller\\CrudBookController:deleteBook' => '?',
            'App\\Controller\\CrudBookController:list' => '?',
            'App\\Controller\\CrudBookController:newBook' => '?',
            'App\\Controller\\CrudBookController:searchByTitle' => '?',
            'App\\Controller\\CrudBookController:updateBook' => '?',
            'App\\Controller\\CrudLibraryController:SearchByName' => '?',
            'App\\Controller\\CrudLibraryController:deleteLibrary' => '?',
            'App\\Controller\\CrudLibraryController:list' => '?',
            'App\\Controller\\CrudLibraryController:newLibrary' => '?',
            'App\\Controller\\CrudLibraryController:updateLibrary' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
